### ISSUE TITLE
USER STORY : Illustrate purpose of application through UI

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#1]
As a **Site User** I can **view the landing page** so that **I can determine the purpose of the application**

## Acceptance Criteria

* AC1 - The landing page must clearly communicating the application's purpose.

* AC2 - The landing page shows the summary advantages of the site.

* AC3 - The landing page encourage the user to want to view more

* AC4 - The "Sign Up," or "Login" must be visible.

### Tasks

- [x] Setup landing page
- [x] Show summary advantages on landing page
- [x] Create button
- [x] Sign-up

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the home.html template to include a clear headline, value proposition, visually appealing design, and visible Sign Up and Login buttons. Also updated the core/urls.py to use the correct template.

You can review changes in this commit: https://github.com/lkilu6456546/RusJamison-asset_inventory-1/commit/a5985ac1908d639ed3c72f8970b82075758c41b4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by RusJamison** [comment]
### Tasks

- [ ] Set-up landing page
- [ ] Set-up sign up
