### ISSUE TITLE
USER STORY : Create scheduled work order

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#10]
As a **Site User** I can **create a calibration or preventative maintenance event on equipment** so that **I make sure equipment is safe to use on patients all the time**

## Acceptance Criteria

* AC1 - Users must only be able to create events for equipment assigned to their facility. 

* AC2 - The equipment history of last service date and next service date must be easily available all the time

* AC3 - It must not easy to delete equipment service history without deleting the whole equipment details.

## Task

- [x] Generate work order form
- [x] Add last date and next service date to the form
- [x] For legal make it not easy to delete service history
