### ISSUE TITLE
USER STORY : Create unscheduled work order

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#11]
As a **Site User** I can **create repair orders to the equipment** so that **I take control in the repairing of equipment**

## Acceptance Criteria

* AC1 -  Users must see an option (e.g., a button or link) to create a new repair (unscheduled work order) on the equipment detail page or inventory page.

* AC2 - The system must provide a unique identifier for each work order (e.g., Work Order Number).

* AC3 - Allow for further repairs in the update section, work order to be closed at end of repair

## Task

- [x] Setup repair form
- [x] Setup unique repair work order identifier
- [x] Create a repair update if repair is not completed on first repair
