### ISSUE TITLE
USER STORY : Equipment status

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#12]
As a **Site User** I can **assign equipment as in use, under repair or decommissioned** so that **I can report to facility management the status of the equipment**

## Acceptance Criteria

* AC1 -  Users must see an option (e.g., a dropdown or button) to update the status of equipment on the equipment detail page.

* AC2 -  Users must only be able to update the status of equipment belonging to their facility. 

* AC3 -  The system must provide the following status options:
In Use
Under Repair
Decommissioned

## Task

- [x] Create equipment status dropdown menu
- [x] Setup users to CRUD their equipment only
- [x] Create equipment status
