### ISSUE TITLE
USER STORY : Manage Facilities and Departments

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#15]
As a **Site Admin** I can **add Facilities and Departments** so that **I can manage who views or add equipment to the facilities and departments**

## Acceptance Criteria

* AC1 - Site Admins must be able to add new facilities via a form that includes:
Facility Name (required).
Location (required).
Description (optional).

* AC2 - Site Admins must be able to add new departments to a facility via a form that includes:
Department Name (required).
Facility (required, pre-filled if accessed through a facility view).

* AC3 - Deleting a facility must also delete its associated departments 

## Task

- [x] Setup admin to give permissions
- [x] Create new departments and facilities in Django admin
- [x] Cascade required when deleting equipment
