### ISSUE TITLE
USER STORY : Approve Users

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#16]
As a **Site Admin** I can **review and then approve or disapprove a User** so that **the right Users always have access to the facility equipment database**

## Acceptance Criteria

* AC1 - The Site Admin must be able to approve or disapprove a user directly from the Django Admin interface .

* AC2 - The list of approved users must display:
Full Name
Email Address
Role
Facility/Department Access
Permissions Management

* AC3 -  Approved users must only be able to access the facilities and departments assigned to them with the permissions granted

## Task

- [x] Setup super user
- [x] Include facilities on signup
- [x] Set super user to physically approve users
