### ISSUE TITLE
USER STORY : View a list of my health facility equipment

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#3]
As a **Site User** I can **view a list of my facility equipment** so that **I can select an equipment to access more details by clicking the highlighted name of the equipment on the equipment list**

## Acceptance Criteria

* AC1 - In equipment list the name of equipment link to the equipment details

* AC2 - View details from general information to scheduled work order and unscheduled work orders

* AC3 - View all equipment under my health facility

## Tasks

- [x] Link name to equipment details
- [x] Link name to equipment scheduled and unscheduled work order
- [x] Select equipment under one facility
