### ISSUE TITLE
USER STORY : View equipment information

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#4]
As a **Site User** I can **click on equipment or scheduled work order or unscheduled work order** so that **I can view  full details of equipment**

## Acceptance Criteria

* AC1 - Equipment tab allows you to view all equipment under your health facility

* AC2 - Scheduled work order button allow user to see all planned work orders

* AC3 - Unscheduled work order button allow user to see all unplanned work orders

* AC4 - The detailed pages for equipment and work orders must be designed to be visually clear, with labels for each field.

## Task

- [x] Create equipment button
- [x] Set-up Scheduled work order button
- [x] Sut-up Unscheduled work order button
- [x] Set-up equipment pages
