### ISSUE TITLE
USER STORY : Add new equipment

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#5]
As a **Site User** I can **add new equipment by clicking add equipment button** so that **I can build my facility equipment database**

## Acceptance Criteria

* AC1 - The form fields must be clear to the user when populating the equipment details.

* AC2 - Any errors to be communicated to the user to be able to correct the error

* AC3 - The date fields must be clear for all users to accommodate users from different continent

* AC4 - Some fields have dropdown menu to confirm to international nomenclature

## Task

- [x] Create equipment form
- [x] Setup required fields
- [x] Create international nomenclature
