### ISSUE TITLE
USER STORY : View equipment in Inventory

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#6]
As a **Site User** I can **access a list of my facility equipment** so that **I can make decision on what action to take on each piece of equipment**

## Acceptance Criteria

* AC1 - View equipment scheduled work order date to arrange services

* AC2 - View equipment age from installation date to replace equipment

* AC3 - View equipment and distribute to other locations

* AC4 - To budget for new equipment using principle any equipment 8 years must be replaced

## Task

- [x] Setup scheduled work order dates
- [x] Setup installation date
- [x] Setup export to PDF
