### ISSUE TITLE
USER STORY : Delete equipment

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#7]
As a **Site User** I can **delete equipment** so that **it is no longer on the facility list**

## Acceptance Criteria

* AC1 - Confirmation (Are you sure you want to delete this equipment?").

* AC2 - If user confirms, equipment will be removed

* AC3 - Deleted equipment must not appear anyway after the delete action

* AC4 - Perform User testing of delete action

## Task

- [x] Create delete button
- [x] Setup user confirmation before delete
- [x] Setup cascade for delete items
- [x] User testing
