### ISSUE TITLE
USER STORY : Update equipment

### ISSUE THREAD

**Issue by RusJamison** [RusJamison/asset_inventory#9]
As a **Site User** I can **update my facility equipment only** so that **I have the latest history on each piece of equipment**

## Acceptance Criteria

* AC1 - Able to change equipment department within same facility for user

* AC2 - Able to correct and information captured earlier

* AC3 - The user must only be allowed to update equipment belonging to their facility

* AC4 - The system must save the updated changes and redirect the user the equipment list. 

## Task

- [x] Setup update equipment
- [x] Setup users to only update their equipment only
- [x] Save updated equipment
